language: go
go:
  - 1.7.6
  - 1.8.3
sudo: false
before_install:
  - gotools=golang.org/x/tools
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go install -v . ./cmd/...
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -v $gotools/cmd/cover
script:
  - export PATH=$PATH:$GOPATH/bin
  - ./goclean.sh
